### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by IAMDROPPE** [pcurz/iptv-auto-activator#1]
What would the implementation method look like?

Detail:
It is clear that it can be run from Node.js in a terminal.

Will there be the possibility to run it on Android without the need for Termux or convert it directly into an apk?

P.D: Excuse the spelling or grammar, I use Google translate

**Comment by xfrcc** [comment]
Yes it is possible, We would have to make an app and implement the solution, but keep in mind that this is intended to run 24/7 so if you're using this in your every day phone it will run out of battery soon.

**Comment by matichewer** [comment]
Me parece que todos somos latinos, después de todo Spliktv solo tiene canales en español.

Estaría genial una aplicacion para Android. Spliktv solo pide 2 activaciones por día. En la app se podría permitir que el usuario decida a qué hora quiere q se ejecute el activador, y listo. Y que también tenga una especie de activación manual, por si justo la activación automática fue con datos móviles. Tener una app siempre será una ventaja ya que se activaría de una, sin necesidad de pasar por la publicidad.

**Comment by IAMDROPPE** [comment]
Tengo una duda
Suponiendo que ('yes') cambie por un token único como haría para especificarlo?

`               btn_veri: 'yes1', 
                btn_ver: 'yes', 
                [id]: 'Pulsa aquí para activar'`
                
Mi duda es porque hay una app la cual el método de activación es similar, pero fue actualizada y el código cambió

`<form id="7526" method="POST"><input type="hidden" name="method_name" value="activate"><input type="hidden" name="token" value="ODViYmQwNTY5Nzc3MDJiZPdOi90ry2jfVA76B5n/yPVVbC1jzaVPmnqywiO+o+x6"><input id="btnactiv" type="submit" style="display: inline;" class="env" value="Pulsa aquí para activar "></form>` 

Donde él (value=) es un token que se actualiza cada vez que se recarga la página. Y no encuentro la forma de especificar el (value=) porque se actualiza cada vez.

**Comment by xfrcc** [comment]
> Tengo una duda Suponiendo que ('yes') cambie por un token único como haría para especificarlo?
> 
> ` btn_veri: 'yes1', btn_ver: 'yes', [id]: 'Pulsa aquí para activar'`
> 
> Mi duda es porque hay una app la cual el método de activación es similar, pero fue actualizada y el código cambió
> 
> `<form id="7526" method="POST"><input type="hidden" name="method_name" value="activate"><input type="hidden" name="token" value="ODViYmQwNTY5Nzc3MDJiZPdOi90ry2jfVA76B5n/yPVVbC1jzaVPmnqywiO+o+x6"><input id="btnactiv" type="submit" style="display: inline;" class="env" value="Pulsa aquí para activar "></form>`
> 
> Donde él (value=) es un token que se actualiza cada vez que se recarga la página. Y no encuentro la forma de especificar el (value=) porque se actualiza cada vez.

Revisa si aquel token se obtiene desde el html y tendrás que parsearlo para sacarlo, en caso de que el html cambie dinamicamente por algun framework entonces tendrás que optar por alguna solucion usando Selenium/Puppeteer/etc

**Comment by IAMDROPPE** [comment]
> > Tengo una duda Suponiendo que ('yes') cambie por un token único como haría para especificarlo?
> > ` btn_veri: 'yes1', btn_ver: 'yes', [id]: 'Pulsa aquí para activar'`
> > Mi duda es porque hay una app la cual el método de activación es similar, pero fue actualizada y el código cambió
> > `<form id="7526" method="POST"><input type="hidden" name="method_name" value="activate"><input type="hidden" name="token" value="ODViYmQwNTY5Nzc3MDJiZPdOi90ry2jfVA76B5n/yPVVbC1jzaVPmnqywiO+o+x6"><input id="btnactiv" type="submit" style="display: inline;" class="env" value="Pulsa aquí para activar "></form>`
> > Donde él (value=) es un token que se actualiza cada vez que se recarga la página. Y no encuentro la forma de especificar el (value=) porque se actualiza cada vez.
> 
> Revisa si aquel token se obtiene desde el html y tendrás que parsearlo para sacarlo, en caso de que el html cambie dinamicamente por algun framework entonces tendrás que optar por alguna solucion usando Selenium/Puppeteer/ ¿Cual es esa otra app?

Para más info de la otra app es (https://www.listasiptvactualizadas.com/activar-kraken-tv/) honestamente la prefiero más y aprovecho de recomendarla... Para uso personal quise adaptar este mismo proyecto para esta app, pero comparando con spliktv el token está en el lugar de (Spliktv=>[value='yes'] [krakenTV=>value='T0k3N/UN1CO'])  y cambia cada vez que se refresca la página, también demora unos segundos en aparecer el botón para activar y al scrapear la página no toma el token de inmediato, por lo cuál tuve que agregar un retraso, pero en cuanto a tomar automáticamente el token se me ha hecho difícil. Para ser sincero cuento solo con conocimientos muy modestos, pero si me apoyan con un indicio podre resolverlo.

**Comment by IAMDROPPE** [comment]
> > > > Tengo una duda Suponiendo que ('yes') cambie por un token único como haría para especificarlo? 
> > > > ` btn_veri: 'yes1', btn_ver: 'yes', [id]: 'Pulsa aquí para activar'`
> > > > Mi duda es porque hay una app la cual el método de activación es similar, pero fue actualizada y el código cambió 
> > > > `<form id="7526" method="POST"><input type="hidden" name="method_name" value="activate"><input type="hidden" name="token" value="ODViYmQwNTY5Nzc3MDJiZPdOi90ry2jfVA76B5n/yPVVbC1jzaVPmnqywiO+o+x6"><input id="btnactiv" type="submit" style="display: inline;" class="env" value="Pulsa aquí para activar "></form>`
> > > > Donde él (value=) es un token que se actualiza cada vez que se recarga la página. Y no encuentro la forma de especificar el (value=) porque se actualiza cada vez.
> > > 
> > > 
> > > Revisa si aquel token se obtiene desde el html y tendrás que parsearlo para sacarlo, en caso de que el html cambie dinamicamente por algun framework entonces tendrás que optar por alguna solucion usando Selenium/Puppeteer/ ¿Cual es esa otra app?
> > 
> > 
> > Para más info de la otra app es ( [https://www.listasiptvactualizadas.com/activar-kraken-tv/ ](https://www.listasiptvactualizadas.com/activar-kraken-tv/)) honestamente la prefiero más y aprovecho de recomendarla... Para uso personal quise adaptar este mismo proyecto para esta app, pero comparando con spliktv el token está en el lugar de (Spliktv=>[value='yes'] [krakenTV=>value='T0k3N/UN1CO']) y cambia cada vez que se refresca la página, también demora unos segundos en aparecer el botón para activar y al scrapear la página no toma el token de inmediato, por lo cuál tuve que agregar un retraso, pero en cuanto a tomar automáticamente el token se me ha hecho difícil. Para ser sincero cuento solo con conocimientos muy modestos, pero si me apoyan con un indicio podre resolverlo.
> 
> La revisé y si, es muy igual al de spliktv (por no decir que los nombre de los div llevan spliktv jaja)
> 
> Probé entrando a la pagina con JavaScript desactivado y el efecto era el mismo, solo que no aparecia el boton de activar (pero de todas formas estaba el token en el html, entonces si es factible usar una solucion sin algun navegador automatizado)
> 
> Noté que el POST es distinto, acá se usa method_name y su valor es 'activate', después se usa token y es el token obtenido obviamente. Esto lo pude ver en el navegador desde el PC, entrando a las herramientas del desarrollador (CTRL+Shift+I) y viendo la pestaña de red, luego hacemos la activacion dando click para ver las solicitudes que hace y su comportamiento. fuera de eso lo distinto son los divs y los mensajes de Error, hice esto no he probado la app pero me dices que tal va, también cambié la forma que saca el token usando el mismo cheerio lo cual corresponde (haré este cambio al de splikTV también y lo subo)
> 
> EDIT: podria cambiar el nombre del repo para ofrecer soluciones para varias Apps de IPTV, y que todos puedan contribuir
> 
> ```
> const axios = require('axios');
> const cheerio = require('cheerio');
> const url = require('url');
> const fs = require('fs');
> 
> const stream = fs.createWriteStream('logs.txt', { flags:'a' });
> const ua = 'Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36';
> 
> const simpleLog = (message) => {
>     const fecha = new Date().toLocaleString('en-US').replace(/,/, '');
>     console.log(`[${fecha}]: ${message}`);
>     stream.write(`[${fecha}]: ${message}\n`);
> }
> 
> 
> const main = async() => {
>     try {
>         let res = await axios({
>             method: 'get',
>             url: 'https://www.listasiptvactualizadas.com/activar-kraken-tv/',
>             headers: {
>                 'User-Agent': ua
>             }
>         });
>         let html = res.data;
>         let $ = cheerio.load(html);
>         const msgActivaste = $('#activarspliktv').first().text().length > 0 ? $('#activarspliktv').first().text() : null;
>         if (!msgActivaste) {
>             const token = $('input[name="token"]').val();
>             simpleLog(`Token: ${token}, activando...`);
>             const data = new url.URLSearchParams({
>                 method_name: 'activate',
>                 token: token
>             });
>             res = await axios({
>                 method: 'post',
>                 url: 'https://www.listasiptvactualizadas.com/activar-kraken-tv',
>                 data: data.toString(),
>                 headers: {
>                     'Content-Type': 'application/x-www-form-urlencoded',
>                     'User-Agent': ua,
>                     'Referer': 'https://www.listasiptvactualizadas.com/activar-kraken-tv',
>                     'Origin': 'https://www.listasiptvactualizadas.com/'
>                 }
>             });
>             html = res.data;
>             $ = cheerio.load(html);
>             const msgActivaste = $('#activarspliktv').first().text().length > 0 ? $('#activarspliktv').first().text() : null;
>             if (msgActivaste.includes('Seras bloqueado por usar diferentes metodos, ponte en contacto con el admin.')) {
>                 simpleLog(msgActivaste);
>                 process.exit(0);
>             }
>             else if (msgActivaste.includes('Activado..!')) {
>                 simpleLog(msgActivaste);
>                 setTimeout(main, 1000 * 60 * 60);
>             }
>         }
>         else {
>             simpleLog(msgActivaste);
>             setTimeout(main, 1000 * 60 * 60);
>         }
>     }
>     catch (e) {
>         simpleLog(JSON.stringify(e));
>         setTimeout(main, 5000);
>     }
> 
> }
> 
> main();
> ```

Por otra parte, yo también estuve investigando y aunque es otro método con el apoyo de un amigo se consolidó el siguiente código quizá pueda ser de utilidad 

`<?php

//composer require mervick/curl-helper
require __DIR__ . '/vendor/autoload.php';

// agarro el token de uso y si no existe agarro el del form
$html = file_get_contents('https://www.listasiptvactualizadas.com/activar-kraken-tv');

preg_match('/Token: (.*?) </', $html, $response_token);
if (is_array($response_token) && isset($response_token[1])) {
	exit("Token: {$response_token[1]}");
}

preg_match('/name="token" value="(.*?)"/', $html, $form_token);
if (!is_array($form_token) || !$form_token[1]) {
	echo 'No encontre el token!';
	//var_dump($form_token, $html);
	exit();
}

// simulo el request
$response = Mervick\CurlHelper::factory()
	->setUrl('https://www.listasiptvactualizadas.com/activar-kraken-tv/')
	->setPostFields([
		'method_name'	=> 'activate',
		'token' 		=> $form_token[1],
	])
	->exec();

// agarro token
preg_match('/Token: (.*?) </', $response['content'], $response_token);
if (is_array($response_token) && isset($response_token[1])) {
	exit("Token: {$response_token[1]}");
}

`

**Comment by IAMDROPPE** [comment]
`<?php

//composer require mervick/curl-helper
require __DIR__ . '/vendor/autoload.php';

// agarro el token de uso y si no existe agarro el del form
$html = file_get_contents('https://www.listasiptvactualizadas.com/activar-kraken-tv');

preg_match('/Token: (.*?) </', $html, $response_token);
if (is_array($response_token) && isset($response_token[1])) {
	exit("Token: {$response_token[1]}");
}

preg_match('/name="token" value="(.*?)"/', $html, $form_token);
if (!is_array($form_token) || !$form_token[1]) {
	echo 'No encontre el token!';
	//var_dump($form_token, $html);
	exit();
}

// simulo el request
$response = Mervick\CurlHelper::factory()
	->setUrl('https://www.listasiptvactualizadas.com/activar-kraken-tv/')
	->setPostFields([
		'method_name'	=> 'activate',
		'token' 		=> $form_token[1],
	])
	->exec();

// agarro token
preg_match('/Token: (.*?) </', $response['content'], $response_token);
if (is_array($response_token) && isset($response_token[1])) {
	exit("Token: {$response_token[1]}");
}`

**Comment by xfrcc** [comment]
> > > > > Tengo una duda Suponiendo que ('yes') cambie por un token único como haría para especificarlo?
> > > > > ` btn_veri: 'yes1', btn_ver: 'yes', [id]: 'Pulsa aquí para activar'`
> > > > > Mi duda es porque hay una app la cual el método de activación es similar, pero fue actualizada y el código cambió
> > > > > `<form id="7526" method="POST"><input type="hidden" name="method_name" value="activate"><input type="hidden" name="token" value="ODViYmQwNTY5Nzc3MDJiZPdOi90ry2jfVA76B5n/yPVVbC1jzaVPmnqywiO+o+x6"><input id="btnactiv" type="submit" style="display: inline;" class="env" value="Pulsa aquí para activar "></form>`
> > > > > Donde él (value=) es un token que se actualiza cada vez que se recarga la página. Y no encuentro la forma de especificar el (value=) porque se actualiza cada vez.
> > > > 
> > > > 
> > > > Revisa si aquel token se obtiene desde el html y tendrás que parsearlo para sacarlo, en caso de que el html cambie dinamicamente por algun framework entonces tendrás que optar por alguna solucion usando Selenium/Puppeteer/ ¿Cual es esa otra app?
> > > 
> > > 
> > > Para más info de la otra app es ( [https://www.listasiptvactualizadas.com/activar-kraken-tv/ ](https://www.listasiptvactualizadas.com/activar-kraken-tv/)) honestamente la prefiero más y aprovecho de recomendarla... Para uso personal quise adaptar este mismo proyecto para esta app, pero comparando con spliktv el token está en el lugar de (Spliktv=>[value='yes'] [krakenTV=>value='T0k3N/UN1CO']) y cambia cada vez que se refresca la página, también demora unos segundos en aparecer el botón para activar y al scrapear la página no toma el token de inmediato, por lo cuál tuve que agregar un retraso, pero en cuanto a tomar automáticamente el token se me ha hecho difícil. Para ser sincero cuento solo con conocimientos muy modestos, pero si me apoyan con un indicio podre resolverlo.
> > 
> > 
> > La revisé y si, es muy igual al de spliktv (por no decir que los nombre de los div llevan spliktv jaja)
> > Probé entrando a la pagina con JavaScript desactivado y el efecto era el mismo, solo que no aparecia el boton de activar (pero de todas formas estaba el token en el html, entonces si es factible usar una solucion sin algun navegador automatizado)
> > Noté que el POST es distinto, acá se usa method_name y su valor es 'activate', después se usa token y es el token obtenido obviamente. Esto lo pude ver en el navegador desde el PC, entrando a las herramientas del desarrollador (CTRL+Shift+I) y viendo la pestaña de red, luego hacemos la activacion dando click para ver las solicitudes que hace y su comportamiento. fuera de eso lo distinto son los divs y los mensajes de Error, hice esto no he probado la app pero me dices que tal va, también cambié la forma que saca el token usando el mismo cheerio lo cual corresponde (haré este cambio al de splikTV también y lo subo)
> > EDIT: podria cambiar el nombre del repo para ofrecer soluciones para varias Apps de IPTV, y que todos puedan contribuir
> > ```
> > const axios = require('axios');
> > const cheerio = require('cheerio');
> > const url = require('url');
> > const fs = require('fs');
> > 
> > const stream = fs.createWriteStream('logs.txt', { flags:'a' });
> > const ua = 'Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36';
> > 
> > const simpleLog = (message) => {
> >     const fecha = new Date().toLocaleString('en-US').replace(/,/, '');
> >     console.log(`[${fecha}]: ${message}`);
> >     stream.write(`[${fecha}]: ${message}\n`);
> > }
> > 
> > 
> > const main = async() => {
> >     try {
> >         let res = await axios({
> >             method: 'get',
> >             url: 'https://www.listasiptvactualizadas.com/activar-kraken-tv/',
> >             headers: {
> >                 'User-Agent': ua
> >             }
> >         });
> >         let html = res.data;
> >         let $ = cheerio.load(html);
> >         const msgActivaste = $('#activarspliktv').first().text().length > 0 ? $('#activarspliktv').first().text() : null;
> >         if (!msgActivaste) {
> >             const token = $('input[name="token"]').val();
> >             simpleLog(`Token: ${token}, activando...`);
> >             const data = new url.URLSearchParams({
> >                 method_name: 'activate',
> >                 token: token
> >             });
> >             res = await axios({
> >                 method: 'post',
> >                 url: 'https://www.listasiptvactualizadas.com/activar-kraken-tv',
> >                 data: data.toString(),
> >                 headers: {
> >                     'Content-Type': 'application/x-www-form-urlencoded',
> >                     'User-Agent': ua,
> >                     'Referer': 'https://www.listasiptvactualizadas.com/activar-kraken-tv',
> >                     'Origin': 'https://www.listasiptvactualizadas.com/'
> >                 }
> >             });
> >             html = res.data;
> >             $ = cheerio.load(html);
> >             const msgActivaste = $('#activarspliktv').first().text().length > 0 ? $('#activarspliktv').first().text() : null;
> >             if (msgActivaste.includes('Seras bloqueado por usar diferentes metodos, ponte en contacto con el admin.')) {
> >                 simpleLog(msgActivaste);
> >                 process.exit(0);
> >             }
> >             else if (msgActivaste.includes('Activado..!')) {
> >                 simpleLog(msgActivaste);
> >                 setTimeout(main, 1000 * 60 * 60);
> >             }
> >         }
> >         else {
> >             simpleLog(msgActivaste);
> >             setTimeout(main, 1000 * 60 * 60);
> >         }
> >     }
> >     catch (e) {
> >         simpleLog(JSON.stringify(e));
> >         setTimeout(main, 5000);
> >     }
> > 
> > }
> > 
> > main();
> > ```
> 
> jaja o son los mismos o son otros que usan los mismos servidores, hay muchas similitudes hasta en la misma interfaz de la app.
> 
> Por otra parte, yo también estuve investigando y aunque es otro método con el apoyo de un amigo, se consolidó el siguiente código, quizá pueda ser de utilidad.
> 
> Está genial que más personas puedan contribuir porque más allá de tener el código, cada quien tiene diferentes métodos y siempre estará genial aprender

Si, no me extrañaria que fueran los mismos, estaba viendo la app y la interfaz es muy similar a SplikTV, pareciera que fuese algun mod o algo

**Comment by matichewer** [comment]
Estaría genial una página web super simple sin publicidad, que al abrirla, automaticamente se ejecuten ambos activadores (el de SplikTV y el de KrakenTV).
Sería como un clon de los activadores oficiales, pero sin la necesidad de ver publicidad, funcional para cualquier ser humano (tan simple como abrir una pagina web)

**Comment by xfrcc** [comment]
> Estaría genial una página web super simple sin publicidad, que al abrirla, automaticamente se ejecuten ambos activadores (el de SplikTV y el de KrakenTV). Sería como un clon de los activadores oficiales, pero sin la necesidad de ver publicidad, funcional para cualquier ser humano (tan simple como abrir una pagina web)

Si, aunque habrian posibles problemas en la pagina web porque no podrás hacer requests a una página de otro dominio (CORS Access-Control-Allow-Origin Header)
Es posible que haga una app mejor, pero el cuando está indefinido aún (tengo que descargar Android Studio etc)

**Comment by xfrcc** [comment]
Descontinuaron el servicio por problemas legales, ahora es cuando se "migran" a KrakenTV jaja...

**Comment by IAMDROPPE** [comment]
> Descontinuaron el servicio por problemas legales, ahora es cuando se "migran" a KrakenTV jaja...

jaja ya me enteré de la noticia.
Si vas a hacer una app mejor, eso sería genial. Cuenta con mi apoyo si necesitas listas m3u prémium o alguna otra cosa.
Aún que si le vas a poner publicidad y que se active 2 veces al día prefiero pagarte una mensualidad XDD

**Comment by pcurz** [comment]
#2
